### ISSUE TITLE
CSRF verification error

### ISSUE THREAD

**Issue by ahoiroman** [ShobuPrime/zammad#1]
Hi there,

using your docker container I am getting CSRF token verification failed on login attempt on all browsers.

**Comment by ShobuPrime** [comment]
Hello @ahoiroman - I remember when I first created the container, I received the error as well.

I personally use HTTPS, and by settings are configured for HTTPS redirection using a certificate from LetsEncrypt.

In the nginx config:

		# Line below supposedly causes CSRF Token Verification Error
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

		# Solution - https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080/45
		proxy_set_header X-Forwarded-Proto https;

Let me know if you need any more help with this.

**Comment by ahoiroman** [comment]
That worked. Thanks :-)
